---
apiVersion: v1
kind: Namespace
metadata:
  name: gitops
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: gitops
data:
  nginx.conf: |-
    #CODE1.0:
    #add the nginx.conf configuration - this will be referenced within the deployment.yaml
    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://localhost:5000/;
            proxy_set_header Host "localhost";
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: gitops
  annotations:
    flux.weave.works/tag.flask: glob:v*
    flux.weave.works/automated: 'true'
  labels:
    role: frontend
    env: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.5-alpine-perl
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: nginx-proxy-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
      - name: flask
        image: docker.io/jprao715/flaskapp:v2
        ports:
        - name: http
          containerPort: 5000
        env:
        - name: APP_NAME
          value: Cedar715.k8s.GitOps
        - name: APP_VERSION
          value: v1.1
      volumes:
      - name: nginx-proxy-config
        configMap:
          name: nginx-conf
